branch-defaults:
  ebdeploy:
    environment: Oslokokeboka-env
environment-defaults:
  Oslokokeboka-env:
    branch: null
    repository: null
global:
  application_name: oslo-kokeboka
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
deploy:
  artifact: dist/frontend.zip
